COMMON_NAME=Comune di Roma
ENTITY_ID=https://spid.comune.roma.it/metadata
KEY_LEN=3072
LOCALITY_NAME=Roma
MD_ALG=sha256
ORGANIZATION_IDENTIFIER=VATIT-02438750586
ORGANIZATION_NAME=Comune di Roma
SPID_SECTOR=private
