name: Push Docker image

on:
  push:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest
    outputs:
      DOCKERHUB_USERNAME: ${{ steps.dockerhub_username.outputs.is_set }}
      DOCKERHUB_TOKEN: ${{ steps.dockerhub_token.outputs.is_set }}
      ALL: ${{ steps.dockerhub_token.outputs.is_set && steps.dockerhub_token.outputs.is_set }}
    steps:
    -
      name: Check DOCKERHUB_USERNAME
      id: dockerhub_username
      run: |
        echo "is_set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
        echo "::set-output name=is_set::${{ secrets.DOCKERHUB_USERNAME != '' }}"
    -
      name: Check DOCKERHUB_TOKEN
      id: dockerhub_token
      run: |
        echo "is_set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        echo "::set-output name=is_set::${{ secrets.DOCKERHUB_TOKEN != '' }}"
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    needs:
    - check_secrets
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      if: ${{ needs.check_secrets.outputs.DOCKERHUB_USERNAME == 'true' }}
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/spid-compliant-certificates
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=edge,branch=master
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      if: ${{ github.event_name != 'pull_request' && needs.check_secrets.outputs.ALL == 'true' }}
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./python
        platforms: |
          linux/amd64
          linux/arm64/v8
        push: ${{ github.event_name != 'pull_request' && needs.check_secrets.outputs.ALL == 'true' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
